[2024-08-23T08:46:48.811+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_wttj_pipeline.bulk_load_task scheduled__2024-08-22T08:30:00+00:00 [queued]>
[2024-08-23T08:46:48.819+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_wttj_pipeline.bulk_load_task scheduled__2024-08-22T08:30:00+00:00 [queued]>
[2024-08-23T08:46:48.819+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 4
[2024-08-23T08:46:48.831+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): bulk_load_task> on 2024-08-22 08:30:00+00:00
[2024-08-23T08:46:48.836+0000] {standard_task_runner.py:60} INFO - Started process 4781 to run task
[2024-08-23T08:46:48.839+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'simple_wttj_pipeline', 'bulk_load_task', 'scheduled__2024-08-22T08:30:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/wttj_pipeline.py', '--cfg-path', '/tmp/tmp8g98mt_s']
[2024-08-23T08:46:48.840+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask bulk_load_task
[2024-08-23T08:46:48.854+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-23T08:46:48.888+0000] {task_command.py:423} INFO - Running <TaskInstance: simple_wttj_pipeline.bulk_load_task scheduled__2024-08-22T08:30:00+00:00 [running]> on host f25666c00f72
[2024-08-23T08:46:48.957+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_wttj_pipeline' AIRFLOW_CTX_TASK_ID='bulk_load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-22T08:30:00+00:00'
[2024-08-23T08:46:59.321+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/wttj_pipeline.py", line 50, in bulk_load
    subprocess.run(['python', '/opt/airflow/ETL/Load/bulk_script_wttj.py', transformed_file_path, log_file], check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/ETL/Load/bulk_script_wttj.py', '/opt/airflow/ETL/Json_transformed/wttj_database_2024-08-23_updated.json', '/opt/airflow/logs/bulk_load_task.log']' returned non-zero exit status 1.
[2024-08-23T08:46:59.332+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=simple_wttj_pipeline, task_id=bulk_load_task, execution_date=20240822T083000, start_date=20240823T084648, end_date=20240823T084659
[2024-08-23T08:46:59.346+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task bulk_load_task (Command '['python', '/opt/airflow/ETL/Load/bulk_script_wttj.py', '/opt/airflow/ETL/Json_transformed/wttj_database_2024-08-23_updated.json', '/opt/airflow/logs/bulk_load_task.log']' returned non-zero exit status 1.; 4781)
[2024-08-23T08:46:59.366+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-23T08:46:59.390+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
